version: "3"
services:
  datenbank:
    image: mysql:latest
    container_name: datenbank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: datenbank
      MYSQL_DATABASE: datenbank
      MYSQL_USER: datenbank
      MYSQL_PASSWORD: datenbank
    volumes:
      - datenbank-speicher:/var/lib/mysql

  datenbank-verwaltung:
    image: adminer:latest
    container_name: datenbank-verwaltung
    restart: always
    ports:
      - "8080:8080"

volumes:
  datenbank-speicher:
