version: "3"
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./webserver-speicher:/usr/share/nginx/html

volumes:
  webserver-speicher:
