version: "3"
services:
  datenbank:
    image: mysql:latest
    container_name: datenbank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: inhaltsverwaltungssystem
      MYSQL_DATABASE: inhaltsverwaltungssystem
      MYSQL_USER: inhaltsverwaltungssystem
      MYSQL_PASSWORD: inhaltsverwaltungssystem
    volumes:
      - datenbank-speicher:/var/lib/mysql

  datenbank-verwaltung:
    image: adminer:latest
    container_name: datenbank-verwaltung
    restart: always
    ports:
      - "8080:8080"

  inhaltsverwaltungssystem:
    image: wordpress:latest
    container_name: inhaltsverwaltungssystem
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: datenbank
      WORDPRESS_DB_USER: inhaltsverwaltungssystem
      WORDPRESS_DB_PASSWORD: inhaltsverwaltungssystem
      WORDPRESS_DB_NAME: inhaltsverwaltungssystem
    volumes:
      - inhaltsverwaltungssystem-speicher:/var/www/html

volumes:
  datenbank-speicher:
  inhaltsverwaltungssystem-speicher:
